name: test
on:
    workflow_call:
        inputs:
          docker-args:
            description: 'Docker build arguments'
            required: false
            type: string
jobs:
  deploy-template:
    runs-on: ubuntu-latest
    steps:
        -
          name: Checkout Repository
          uses: actions/checkout@v2
        -
          name: Set environment variables
          continue-on-error: true
          run: |
            echo "VARIABLE=PIZDA" >> $GITHUB_ENV
            echo "ENVIRONMENT=dev" >> $GITHUB_ENV

        -
          name: check variables in env
          run: |
            echo $VARIABLE

        - name: check variables in env.context
          run: |
            echo ${{ env.VARIABLE }}

        - name: check variable in input
          run: |
            echo ${{ inputs.docker-args }}


        -
          name: Format build args
          id: build-args
          run: |
            echo "Input docker-args:"
            echo "${{ inputs.docker-args }}"

            echo "Current environment variables:"
            env
            echo "${{ inputs.docker-args }}" > /tmp/build-args.txt
            formatted_args=$(envsubst < /tmp/build-args.txt)
            echo "Formatted arguments:"
            echo "$formatted_args"
            echo "FORMATTED_ARGS<<EOF" >> $GITHUB_OUTPUT
            echo "$formatted_args" >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT


        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
        -
          name: Docker Build
          uses: docker/build-push-action@v5
          with:
            context: .
            push: false
            load: true
            tags: ${{ github.run_id }}
            # build-args: ENVIRONMENT=${{ env.ENVIRONMENT }} ${{ inputs.docker-args }}
            build-args: ${{ steps.build-args.outputs.FORMATTED_ARGS }}
        -
          name: run docker image with command cat /tmp/variable.txt
          run: |
            docker run ${{ github.run_id }} cat /tmp/variable.txt
